### ISSUE TITLE
[Wishlist] Bioc3.8 Release

### ISSUE THREAD

**Issue by nhejazi** [nhejazi/methyvim#29]
# Working feature list for future releases:

## Additional Options
- ~~add support for continuous treatments using `tmle.npvi`~~
- [ ] add support for doubly robust TMLEs using `drtmle`
- [ ] add support for influence function estimates and shrinkage with `drtmle` + `limma`
- [ ] add support for filtering/pre-screening using nonparametric methods (e.g., `adaptest`)

## Big Picture
- [ ] support for finding/evaluating differentially methylated regions (DMR) in a flexible manner as per #35
- [ ] flexible definition of CpG clusters using information about the design of Illumina assays (e.g., using the ["probe lasso" approach](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4304833/))

**Comment by rachaelvphillips** [comment]
**- nonparametric filtering/pre-screening** 

**- informed, flexible clustering** 
Currently, this step disregards probe location. Ideally, this window should flexibly vary depending on the genomic region of the probe. This is because arrays, like the Illumina Methylation array, are inherently biased in their probe design. Specifically, the array is skewed towards gene promoters and CpG islands. Incorporation of an informed, flexible window based approach would acknowledge this bias, leveraging information from the highly probed sites but also the putatively important, but largely ignored, intergenic regions. 

**- nonparametric DMR functionality** tied with this informed, flexible window approach

**Comment by nhejazi** [comment]
The above will not be addressed in time for the BioC 3.7 release, but it would still be good to address these at some later date --- optimistically, by the time of the BioC 3.8 release in ~November.

**Comment by nhejazi** [comment]
stale
